"""
SignalRepository — all database operations for the SIGNAL table.

The SIGNAL table is append-only. Every generated signal is a permanent
record. The current signal for any ticker is always the row with the
latest created_at — never a stored "current" value.

This append-only design is an architectural invariant:
    - It gives you a full audit trail of every signal ever generated.
    - The chatbot and suggestion engine can reason over signal history.
    - You can replay what signals looked like at any point in the past.

Depends on:
    BaseRepository  — session management and context manager
    SignalModel     — the ORM class mapping to the signal table
    SignalValue     — enum for BUY / HOLD / SELL

Exposes:
    add(signal)                     — insert a new signal row (never update)
    get_latest(symbol)              — most recent signal for one ticker
    get_latest_all_tickers()        — most recent signal for every ticker
    get_latest_timestamp(symbol)    — just the timestamp of the latest signal
    get_history(symbol, limit)      — recent signal history for one ticker
    get_by_id(signal_id)            — fetch one signal by its UUID

Key rules:
    - NEVER call session.query(...).update() on this table.
    - NEVER modify a SignalModel object after it has been added.
    - get_latest() returns None if no signal exists yet — never raises.
    - get_latest_timestamp() is used by SuggestionEngine for staleness checks.
"""

from __future__ import annotations

from datetime import datetime

from sqlalchemy.orm import Session

from src.data.database import SignalModel
from src.data.repositories.base import BaseRepository
from src.utils.types import SignalValue


class SignalRepository(BaseRepository):
    """
    Reads and writes the SIGNAL table.

    The most important constraint on this repository: it is append-only.
    add() is the only write operation. There is no update() method and
    there never will be — that is intentional, not an oversight.

    Usage:
        with SignalRepository(session) as repo:
            repo.add(SignalModel(
                ticker="AAPL",
                value=SignalValue.BUY.value,
                probability=0.82,
                model_name="xgboost",
                fwd_days=5,
            ))

        # Read the current signal
        with SignalRepository(session) as repo:
            signal = repo.get_latest("AAPL")
    """

    def __init__(self, session: Session) -> None:
        """
        Args:
            session: Active SQLAlchemy Session from Database.get_session().
        """
        super().__init__(session)

    def add(self, signal: SignalModel) -> None:
        """
        Insert a new signal row.

        This is the ONLY write operation on the signal table. Never call
        this to "update" an existing signal — always insert a new row.
        The current signal is always derived from the latest created_at.

        Does not commit — commit is handled by the context manager or
        by the caller explicitly.

        Args:
            signal: A fully constructed SignalModel instance. The id and
                    created_at fields are auto-generated by the ORM if
                    not provided.

        Example:
            signal = SignalModel(
                ticker="AAPL",
                value=SignalValue.BUY.value,
                probability=0.82,
                model_name="xgboost",
                fwd_days=5,
            )
            repo.add(signal)
        """
        self._session.add(signal)

    def get_latest(self, symbol: str) -> SignalModel | None:
        """
        Fetch the most recent signal for one ticker.

        "Most recent" means the row with the highest created_at timestamp.
        If two signals were generated at the exact same second (shouldn't
        happen in practice), the one with the higher UUID is returned —
        consistent but arbitrary.

        Args:
            symbol: The ticker symbol, e.g. "AAPL".

        Returns:
            The most recent SignalModel row, or None if no signals exist
            yet for this ticker. None is a normal result for a newly
            onboarded ticker that hasn't run inference yet.
        """
        return (
            self._session.query(SignalModel)
            .filter(SignalModel.ticker == symbol)
            .order_by(SignalModel.created_at.desc())
            .first()
        )

    def get_latest_all_tickers(self) -> dict[str, SignalModel]:
        """
        Fetch the most recent signal for every ticker that has one.

        Used by InferenceOrchestrator to assemble the full signal picture
        before running AlertEvaluator and SuggestionEngine.

        This uses a subquery to efficiently get the latest row per ticker
        rather than fetching all signals and filtering in Python.

        How the subquery works:
            1. Inner query: for each ticker, find the MAX(created_at).
               This gives you a table of (ticker, latest_timestamp) pairs.
            2. Outer query: join back to the signal table to get the full
               row that matches each (ticker, latest_timestamp) pair.

        Returns:
            Dict mapping symbol → most recent SignalModel.
            Tickers with no signals are not included in the result.

        Example result:
            {
                "AAPL": <SignalModel ticker=AAPL value=BUY ...>,
                "MSFT": <SignalModel ticker=MSFT value=HOLD ...>,
            }
        """
        from sqlalchemy import func

        # Step 1 — subquery: find the latest created_at per ticker
        # func.max() generates MAX() in SQL
        # group_by(SignalModel.ticker) groups the results per ticker
        # .subquery() turns this into a subquery we can join against
        latest_per_ticker = (
            self._session.query(
                SignalModel.ticker,
                func.max(SignalModel.created_at).label("latest_at"),
            )
            .group_by(SignalModel.ticker)
            .subquery()
        )

        # Step 2 — join the full signal table against the subquery
        # This gives us the full SignalModel row for each latest timestamp
        rows = (
            self._session.query(SignalModel)
            .join(
                latest_per_ticker,
                (SignalModel.ticker == latest_per_ticker.c.ticker)
                & (SignalModel.created_at == latest_per_ticker.c.latest_at),
            )
            .all()
        )

        return {row.ticker: row for row in rows}

    def get_latest_timestamp(self, symbol: str) -> datetime | None:
        """
        Return the created_at timestamp of the most recent signal.

        Used by SuggestionEngine's staleness check to decide whether a
        new suggestion needs to be generated. Fetching just the timestamp
        is more efficient than fetching the full SignalModel row when
        the signal data itself isn't needed.

        Args:
            symbol: The ticker symbol.

        Returns:
            The datetime of the most recent signal, or None if no signals
            exist yet for this ticker.
        """
        from sqlalchemy import func

        result = (
            self._session.query(func.max(SignalModel.created_at))
            .filter(SignalModel.ticker == symbol)
            .scalar()
        )
        return result

    def get_history(self, symbol: str, limit: int = 30) -> list[SignalModel]:
        """
        Fetch recent signal history for one ticker, newest first.

        Used by the chatbot to give the LLM context about how signals
        have been trending for a ticker. Also useful for debugging —
        you can see exactly what signals were generated and when.

        Args:
            symbol: The ticker symbol.
            limit: Maximum number of rows to return. Defaults to 30.
                   Pass a smaller number for chatbot context to keep
                   the prompt size manageable.

        Returns:
            List of SignalModel rows ordered newest first, up to `limit`.
            Empty list if no signals exist for this ticker.
        """
        return (
            self._session.query(SignalModel)
            .filter(SignalModel.ticker == symbol)
            .order_by(SignalModel.created_at.desc())
            .limit(limit)
            .all()
        )

    def get_by_id(self, signal_id: str) -> SignalModel | None:
        """
        Fetch one signal by its UUID primary key.

        Used when an AlertModel or SuggestionLogModel holds a
        triggering_signal_id and you need to retrieve the full signal
        that caused it.

        Args:
            signal_id: The UUID string of the signal row.

        Returns:
            The SignalModel row, or None if not found.
        """
        return self._session.get(SignalModel, signal_id)

    def get_by_value(
        self,
        symbol: str,
        value: SignalValue,
        limit: int = 10,
    ) -> list[SignalModel]:
        """
        Fetch recent signals for a ticker filtered by signal value.

        Useful for asking questions like "how many BUY signals has AAPL
        generated in the last N signals?" — used by the chatbot and
        suggestion engine for trend reasoning.

        Args:
            symbol: The ticker symbol.
            value: The signal value to filter on (BUY, HOLD, or SELL).
            limit: Maximum number of rows to return. Defaults to 10.

        Returns:
            List of matching SignalModel rows, newest first.
        """
        return (
            self._session.query(SignalModel)
            .filter(
                SignalModel.ticker == symbol,
                SignalModel.value == value.value,
            )
            .order_by(SignalModel.created_at.desc())
            .limit(limit)
            .all()
        )